name: agendacultural
description: Cultura.CE

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.5.2
  http: ^1.3.0
  provider: ^6.1.2
  google_fonts: ^4.0.1
  awesome_dialog: ^3.2.1
  readmore: ^3.0.0
  step_progress_indicator: ^1.0.2
  flutter_switch: ^0.3.2
  group_button: ^5.3.4
  intl: 0.19.0 # dart_date depends this
  google_maps_flutter: ^2.10.1
  url_launcher: ^6.3.1
  geolocator: ^13.0.2
  dropdown_search: ^6.0.2
  dart_date: ^1.4.0
  flutter_easyloading: 3.0.5
  uuid: ^4.5.1
  flutter_svg: ^2.0.17
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  flutter_modular: ^6.3.4
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mobx_codegen: ^2.7.0
  build_runner: ^2.4.15

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "imagens/iconelaranha.png"
  min_sdk_android: 20
  web:
    generate: true
    image_path: "imagens/iconelaranha.png"
    background_color: "#ffE83c3b"
    theme_color: "#ffE83c3b"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - imagens/